// Base weather configs — assumes day + dark mode as defaults
// Modifiers adjust for night and light mode

import type { WeatherCondition, WeatherLayerConfig } from "../animatedBG"

const noLightning = {
  enabled: false,
  flashColor: "#FFFFFF",
  flashOpacity: 0,
  intervalRange: [0, 0] as [number, number],
  flashDuration: 0,
  rumbleEnabled: false,
}

export const weatherConfigs: Record<WeatherCondition, WeatherLayerConfig> = {
  sunny: {
    sky: {
      angle: 180,
      stops: [
        { color: "#1a3a5c", position: 0 },
        { color: "#2d6187", position: 30 },
        { color: "#93E6E6", position: 70 },
        { color: "#84C7D0", position: 100 },
      ],
      glowColor: "#93E6E6",
      glowIntensity: 0.15,
      breatheDuration: 8,
    },
    atmosphere: {
      clouds: {
        count: 2,
        color: "rgba(132, 199, 208, 0.15)",
        opacity: 0.3,
        speedRange: [8, 15],
        sizeRange: [15, 25],
        blurRange: [20, 40],
        verticalRange: [5, 25],
      },
      hazeOpacity: 0.05,
      hazeColor: "rgba(147, 230, 230, 0.1)",
      fogEnabled: false,
    },
    particles: {
      type: "sunray",
      count: 10,
      color: "#93E6E6",
      opacity: 0.12,
      sizeRange: [100, 300],
      speedRange: [0.3, 0.8],
      windAngle: 0,
      glowEnabled: true,
      glowColor: "#93E6E6",
    },
    lightning: noLightning,
    transitionDuration: 1.5,
  },

  cloudy: {
    sky: {
      angle: 180,
      stops: [
        { color: "#0a1e33", position: 0 },
        { color: "#1a3a5c", position: 40 },
        { color: "#2d5070", position: 70 },
        { color: "#5F5069", position: 100 },
      ],
      breatheDuration: 10,
    },
    atmosphere: {
      clouds: {
        count: 5,
        color: "rgba(95, 80, 105, 0.4)",
        opacity: 0.5,
        speedRange: [10, 20],
        sizeRange: [20, 35],
        blurRange: [15, 30],
        verticalRange: [5, 40],
      },
      hazeOpacity: 0.1,
      hazeColor: "rgba(95, 80, 105, 0.15)",
      fogEnabled: false,
    },
    particles: {
      type: "dust",
      count: 25,
      color: "#84C7D0",
      opacity: 0.15,
      sizeRange: [1, 3],
      speedRange: [0.2, 0.6],
      windAngle: -5,
      drift: 15,
    },
    lightning: noLightning,
    transitionDuration: 1.5,
  },

  overcast: {
    sky: {
      angle: 180,
      stops: [
        { color: "#0a1520", position: 0 },
        { color: "#1a2a3a", position: 30 },
        { color: "#2a3a4a", position: 60 },
        { color: "#3a4a55", position: 100 },
      ],
      breatheDuration: 0, // static — oppressive feel
    },
    atmosphere: {
      clouds: {
        count: 10,
        color: "rgba(42, 58, 74, 0.6)",
        opacity: 0.7,
        speedRange: [5, 12],
        sizeRange: [25, 45],
        blurRange: [10, 25],
        verticalRange: [0, 50],
      },
      hazeOpacity: 0.2,
      hazeColor: "rgba(42, 58, 74, 0.25)",
      fogEnabled: true,
      fogColor: "rgba(42, 58, 74, 0.3)",
      fogHeight: 15,
    },
    particles: {
      type: "none",
      count: 0,
      color: "#84C7D0",
      opacity: 0,
      sizeRange: [0, 0],
      speedRange: [0, 0],
      windAngle: 0,
    },
    lightning: noLightning,
    transitionDuration: 1.5,
  },

  rain: {
    sky: {
      angle: 180,
      stops: [
        { color: "#050d18", position: 0 },
        { color: "#0f2035", position: 30 },
        { color: "#1a3550", position: 60 },
        { color: "#2a4a65", position: 100 },
      ],
      breatheDuration: 12,
    },
    atmosphere: {
      clouds: {
        count: 7,
        color: "rgba(26, 53, 80, 0.5)",
        opacity: 0.6,
        speedRange: [12, 22],
        sizeRange: [20, 40],
        blurRange: [12, 25],
        verticalRange: [0, 35],
      },
      hazeOpacity: 0.15,
      hazeColor: "rgba(26, 53, 80, 0.2)",
      fogEnabled: true,
      fogColor: "rgba(26, 53, 80, 0.2)",
      fogHeight: 10,
    },
    particles: {
      type: "rain",
      count: 200,
      color: "#93E6E6",
      opacity: 0.35,
      sizeRange: [15, 30],
      speedRange: [800, 1200],
      windAngle: -10,
      splashEnabled: true,
      glowEnabled: true,
      glowColor: "rgba(147, 230, 230, 0.3)",
    },
    lightning: noLightning,
    transitionDuration: 1.5,
  },

  thunderstorm: {
    sky: {
      angle: 180,
      stops: [
        { color: "#020810", position: 0 },
        { color: "#0a1520", position: 25 },
        { color: "#1a1a2e", position: 50 },
        { color: "#2a1a3a", position: 75 },
        { color: "#5F5069", position: 100 },
      ],
      glowColor: "#AA3E98",
      glowIntensity: 0.08,
      breatheDuration: 6,
    },
    atmosphere: {
      clouds: {
        count: 12,
        color: "rgba(26, 26, 46, 0.7)",
        opacity: 0.8,
        speedRange: [18, 30],
        sizeRange: [25, 50],
        blurRange: [8, 20],
        verticalRange: [0, 45],
      },
      hazeOpacity: 0.25,
      hazeColor: "rgba(42, 26, 58, 0.3)",
      fogEnabled: true,
      fogColor: "rgba(26, 26, 46, 0.35)",
      fogHeight: 20,
    },
    particles: {
      type: "rain",
      count: 300,
      color: "#84C7D0",
      opacity: 0.4,
      sizeRange: [18, 35],
      speedRange: [1000, 1500],
      windAngle: -20,
      splashEnabled: true,
      glowEnabled: true,
      glowColor: "rgba(132, 199, 208, 0.25)",
    },
    lightning: {
      enabled: true,
      flashColor: "#AA3E98",
      flashOpacity: 0.3,
      intervalRange: [3, 8],
      flashDuration: 0.15,
      rumbleEnabled: true,
    },
    transitionDuration: 2,
  },

  snow: {
    sky: {
      angle: 180,
      stops: [
        { color: "#0a1a2e", position: 0 },
        { color: "#1a2e45", position: 35 },
        { color: "#2d5070", position: 65 },
        { color: "#84C7D0", position: 100 },
      ],
      glowColor: "#93E6E6",
      glowIntensity: 0.1,
      breatheDuration: 10,
    },
    atmosphere: {
      clouds: {
        count: 4,
        color: "rgba(132, 199, 208, 0.2)",
        opacity: 0.4,
        speedRange: [6, 12],
        sizeRange: [20, 35],
        blurRange: [20, 40],
        verticalRange: [0, 25],
      },
      hazeOpacity: 0.12,
      hazeColor: "rgba(132, 199, 208, 0.1)",
      fogEnabled: true,
      fogColor: "rgba(132, 199, 208, 0.15)",
      fogHeight: 12,
    },
    particles: {
      type: "snow",
      count: 150,
      color: "#F9F9F9",
      opacity: 0.6,
      sizeRange: [2, 6],
      speedRange: [50, 150],
      windAngle: -3,
      drift: 30,
      glowEnabled: true,
      glowColor: "rgba(147, 230, 230, 0.4)",
    },
    lightning: noLightning,
    transitionDuration: 1.5,
  },
}
